name: Global Variable Groups

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - globalvariables.yaml
      - template-purchase.yaml
      - template-platform.yaml
      - .github/workflows/variable-groups.yml

jobs:
  inject-and-print:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Inject variable groups
        uses: lindluni/actions-variable-groups@main
        with:
          org: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          groups: |
            globalvariables.yaml
            template-purchase.yaml
            template-platform.yaml
      
      - name: Print variables
        run: env | sort

      - name: Use PLATFORM NAME
        run: echo "Using PLATFORM NAME: $PLATFORM_NAME"
